MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet101_conv5_body
  NUM_CLASSES: 3
  FASTER_RCNN: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  BASE_LR: 0.00125
  GAMMA: 0.1
  MAX_ITER: 180000
  STEPS: [0, 120000, 160000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
RESNETS:
  STRIDE_1X1: False  # default True for MSRA; False for C2 or Torch models
  TRANS_FUNC: bottleneck_transformation
  NUM_GROUPS: 32
  WIDTH_PER_GROUP: 8
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  WEIGHTS: model_files/resnet/X-101-32x8d.pkl
  DATASETS: ('cbis_ddsm_train', 'cbis_ddsm_val')
  SCALES: (1100,)
  MAX_SIZE: 1700
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
TEST:
  DATASETS: ('cbis_ddsm_test',)
  SCALES: (1100,)
  MAX_SIZE: 1700
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
  FORCE_JSON_DATASET_EVAL: True
  WEIGHTS: /home/xth/codes/python/Detectron/tmp/detectron-output/train/cbis_ddsm_train:cbis_ddsm_val/generalized_rcnn/model_final.pkl
  # -- Test time augmentation example -- #
  # BBOX_AUG:
  #   ENABLED: True
  #   SCORE_HEUR: UNION  # AVG NOTE: cannot use AVG for e2e model
  #   COORD_HEUR: UNION  # AVG NOTE: cannot use AVG for e2e model
  #   H_FLIP: True
  #   SCALES: (600, 1000)
  #   MAX_SIZE: 2000
  #   SCALE_H_FLIP: True
  #   SCALE_SIZE_DEP: False
  #   AREA_TH_LO: 2500   # 50^2
  #   AREA_TH_HI: 32400  # 180^2
  #   ASPECT_RATIOS: ()
  #   ASPECT_RATIO_H_FLIP: False
  # BBOX_VOTE:
  #   ENABLED: True
  #   VOTE_TH: 0.9
  # -- Test time augmentation example -- #
OUTPUT_DIR: .
