MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet101_conv5_body
  NUM_CLASSES: 3
  FASTER_RCNN: True
NUM_GPUS: 4
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  BASE_LR: 0.005
  GAMMA: 0.1
  # MAX_ITER: 180000
  # STEPS: [0, 120000, 160000]
  MAX_ITER: 80000
  STEPS: [0, 25000, 50000, 70000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
RESNETS:
  STRIDE_1X1: False  # default True for MSRA; False for C2 or Torch models
  TRANS_FUNC: bottleneck_transformation
  NUM_GROUPS: 32
  WIDTH_PER_GROUP: 8
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  WEIGHTS: model_files/resnet/X-101-32x8d.pkl
  DATASETS: ('cbis_ddsm_train_filtered', 'cbis_ddsm_val_filtered')
  SCALES: (700,)
  MAX_SIZE: 1300
  IMS_PER_BATCH: 1
  FG_FRACTION: 0.2
  FG_THRESH: 0.2
  BG_THRESH_HI: 0.2
#  BBOX_THRESH: 0.5
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  RPN_POSITIVE_OVERLAP: 0.5
  RPN_NEGATIVE_OVERLAP: 0.2
  RPN_FG_FRACTION: 0.2
  RPN_NMS_THRESH: 0.1
TEST:
  DATASETS: ('cbis_ddsm_test_filtered',)
  # SCALES: (1100,)
  # MAX_SIZE: 1700
  SCALES: (800,)
  MAX_SIZE: 1900
  NMS: 0.3
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 400
  # rpn_PRE_NMS_TOP_N: 3000  # Per FPN level
  # RPN_POST_NMS_TOP_N: 1000  # Per FPN level  
  RPN_NMS_THRESH: 0.3
  # SCORE_THRESH: 0.3  # by default, 0.05
  FORCE_JSON_DATASET_EVAL: True
  WEIGHTS: /home/xth/projects/Detectron/model_files/fasterrcnn/X-101-32x8d-FPN_cbis_filtered/model_final.pkl
  # -- Test time augmentation example -- #
  BBOX_AUG:
    ENABLED: True
    SCORE_HEUR: UNION  # AVG NOTE: cannot use AVG for e2e model
    COORD_HEUR: UNION  # AVG NOTE: cannot use AVG for e2e model
    H_FLIP: False
    SCALES: (500,)
    #SCALES: (600, 700, 800, 900, 1000, 1200)    
    MAX_SIZE: 1900
    SCALE_H_FLIP: True
    SCALE_SIZE_DEP: False
    # AREA_TH_LO: 100   # 50^2
    # AREA_TH_HI: 40000  # 180^2
    ASPECT_RATIOS: (0.8,)
    ASPECT_RATIO_H_FLIP: False
  BBOX_VOTE:
    ENABLED: True
    VOTE_TH: 0.85
    # SCORING_METHOD: AVG
  # -- Test time augmentation example -- #
OUTPUT_DIR: .